server:
  port: 8088
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource