server:
  port: 8088
  servlet:
    context-path: /
spring:
  profiles:
    include: security
  datasource:
    url: jdbc:mysql://${security.datasource.host}:3306/ss_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: ${security.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource