package com.example.helloworld.controller;

import com.example.helloworld.entity.RoomEntity;
import com.example.helloworld.repository.RoomRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/room") // This means URL's start with /room (after Application path)
public class RoomController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RoomRepository roomRepository;


    @GetMapping(path = "/all")
    public @ResponseBody Iterable<RoomEntity> getAllRooms() {
        // This returns a JSON or XML with the users
        return roomRepository.findAll();
    }

    @GetMapping(path = "/remain") // Map ONLY POST Requests
    public @ResponseBody Long getRemainRoomNumber() {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Iterable<RoomEntity> rooms = roomRepository.findAll();
        Long remainNumber = 0L;
        for (RoomEntity room : rooms) {

        }
        return remainNumber;
    }
}